---
title: "teaching"
---
This page outlines my history of teaching and research mentorship.

---

# lab instructor
**Jan 2020 - May 2022**\
University of Pittsburgh\
Course: Hearing Science\

**Aug 2020 - Dec 2021**\
University of Pittsburgh\
Course: Anatomy & Physiological of Hearing\


# guest lecturer
**Feb 2023**\
University of Pittsburgh\
Course: Speech Perception Across the Lifepspan\
Topic: Perceptual Learning\

**May 2022**\
University of Pittsburgh\
Course: Hearing Science\
Topic: Hearing Impairment\


# mentorship
**Aug 2023 - Aug 2024**\
University of Pittsburgh\
Mentees: Alexa Chromey, Danielle Schramek, Emily Hoffman, Emily Wenko, Jessica Strauss\
Topic: Task-Irrelevant Perceptual Learning\

**Jan 2022 - Dec 2022**\
Veterans Affairs Medical Center of Pittsburgh\
Mentee: Lauren Stadel, AuD\
Topic: Veteran-Appropriate Norms for Central Auditory Processing Tests\

**Sep 2019 - Aug 2020**\
Veterans Affairs Medical Center of Pittsburgh\
Mentee: Erin Casey, AuD\
Topic: Memory Load of Central Auditory Processing Tests Administered to Veterans\

